### ISSUE TITLE
course-settings - Add the correct course name

### ISSUE THREAD

**Issue by zlw11063** [byuitechops/course-settings#8]
This will need to meet online and campus specific course naming conventions.

**Comment by danverde** [comment]
Online naming conventions are fixed in this commit to [create-course-object].(https://github.com/byuitechops/create-course-object/commit/49bdffcdcff7ed73444fa43dd28612f64ffd13f1)

**Comment by danverde** [comment]
What are campus naming conventions?

**Comment by zlw11063** [comment]
This looks like its working?
